apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-redis
  template:
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          name: 6379tcp01
          protocol: TCP
        volumeMounts:
        - mountPath: /opt
          name: vol1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: nfs-json-data
