apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: migration
        envFrom:
        - configMapRef:
            name: flyway
            optional: false
        - secretRef:
            name: flyway
            optional: false
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4
